server:
  servlet:
    context-path: /
  port: 9191
 
spring:
  application:
    name: apoiador-requisitante
    version: 0.0.1
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

clients:
  jira:
    url: https://www.cnj.jus.br/jira
    user: bot.revisor.pje
    pass: b@tPJe123
  slack:
    url: https://slack.com/api/
    token: ${SERVICE_SLACK_TOKEN:my-slack-bot-token}
  gitlab:
    url: https://git.cnj.jus.br
    token: QrbQBwcaHs_zB7-t5L4Q
  telegram:
    url: https://api.telegram.org/
    token: bot757944457:AAHOL1HpW-zZK1UHeubf-drbpr3OXPVnkbY
  rocketchat:
    url: https://rocketchat.cloud.pje.jus.br/
    userid: cmDGzkw2PfkzGt5x9
    token: k_fHf6O8VGTLVnvm1m145tmEEBVIzJL0XnxcQlxaQhN

project:
  documentation:
    url: https://docs.pje.jus.br
    manual-revisao-codigo: ${PROJECT_DOCUMENTATION_MANUAL_REVISAO_CODIGO:my-documentation-revisao-codigo-url}
  jira.filters:
    pendentes-geral: ${JIRA_FILTERS_ISSUES_PENDENTES_GERAL:0}
  telegram.channel:
    name: pjenews
    url: https://telegram.me/pjenews
    message-test: -1001507695075
    pje-news-id: '@pjenews'
    geral: ${PROJECT_TELEGRAM_CHANNEL_GENERAL:my-telegram-general-channel-id}
  rocketchat:
    channel:
      message-test: message-test
      grupo-revisor-id: ${PROJECT_ROCKETCHAT_CHANNEL_GRUPO_REVISOR:my-grupo-revisor-channel}
      grupo-negocial-id: ${PROJECT_ROCKETCHAT_CHANNEL_GRUPO_NEOGIAL:my-grupo-neogical-channel}
      pje-news-id: ${PROJECT_ROCKETCHAT_CHANNEL_PJENEWS:my-pjenews-channel}
      pje-dev-platform-id: ${PROJECT_ROCKETCHAT_CHANNEL_PJEDEVPLATFORM:my-pjedevplatform-channel}
      geral: GENERAL
  slack:
    channel:
      triage-bot-id: ${PROJECT_SLACK_CHANNEL_BOT_TRIAGEM:my-triage-bot-channel}
      grupo-revisor-id: ${PROJECT_SLACK_CHANNEL_GRUPO_REVISOR:my-grupo-revisor-channel}
      grupo-negocial-id: ${PROJECT_SLACK_CHANNEL_GRUPO_NEOGIAL:my-grupo-neogical-channel}
      pje-news-id: ${PROJECT_SLACK_CHANNEL_PJENEWS:my-pjenews-channel}
      geral: ${PROJECT_SLACK_CHANNEL_GENERAL:general}